networks:
  local-network:
    driver: bridge

services:
  # 后端
  app:
    build:
      context: ../../radp-desensitization-app
      dockerfile: Dockerfile
    image: xooooooooox/radp-desensitization-app:latest
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: ${appPort}
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/radp-desensitization-admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      SPRING_REDIS_HOST: redis
    volumes:
      - ./volumes/logs:/data/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${appPort}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-network